/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.mudkipavenger.moodle_equation_creator.display;

import com.github.mudkipavenger.moodle_equation_creator.Tree.NodeTreebuilder;
import com.github.mudkipavenger.moodle_equation_creator.wildcard.WildCard;
import com.github.mudkipavenger.moodle_equation_creator.wildcard.WildCardManager;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.Objects;

/**
 *
 * @author levi
 */
public class MEC_GUI extends javax.swing.JFrame {

    /**
     * Creates new form TestGui
     */
    public MEC_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newWildCardDialog = new javax.swing.JDialog();
        newWildCardDialog_nameLabel = new java.awt.Label();
        newWildCardDialog_okButton = new javax.swing.JButton();
        newWildCardDialog_rangeLabel = new javax.swing.JLabel();
        newWildCardDialog_enterNameLabel = new javax.swing.JLabel();
        newWildCardDialog_nameTextField = new javax.swing.JTextField();
        newWildCardDialog_minTextField = new javax.swing.JTextField();
        newWildCardDialog_toLabel = new javax.swing.JLabel();
        newWildCardDialog_maxTextField = new javax.swing.JTextField();
        newWildCardDialog_intervalLabel = new javax.swing.JLabel();
        newWildCardDialog_intervalTextField = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ExpressionsPanel = new javax.swing.JPanel();
        ExpressionsPanel_outputTextAreaScollPane = new javax.swing.JScrollPane();
        ExpressionsPanel_outputTextArea = new javax.swing.JTextArea();
        ExpressionsPanel_directionsLabel1 = new javax.swing.JLabel();
        ExpressionsPanel_inputLabel = new javax.swing.JLabel();
        ExpressionsPanel_copyButton = new javax.swing.JButton();
        ExpressionsPanel_inputTextAreaScollPane = new javax.swing.JScrollPane();
        ExpressionsPanel_inputTextArea = new javax.swing.JTextArea();
        ExpressionsPanel_convertButton = new javax.swing.JButton();
        ExpressionsPanel_directionsLabel2 = new javax.swing.JLabel();
        ExpressionsPanel_outputLabel = new javax.swing.JLabel();
        ExpressionsPanel_insertWildcardsButton = new javax.swing.JButton();
        WildcardPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        WildcardPanel_wildcardTable = new javax.swing.JTable();
        WildcardPanel_addNewWildcardButton = new javax.swing.JButton();

        newWildCardDialog.setTitle("Add New WildCard");
        newWildCardDialog.setName(""); // NOI18N
        newWildCardDialog.setSize(new java.awt.Dimension(400, 300));
        newWildCardDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                newWildCardDialogWindowActivated(evt);
            }
        });

        newWildCardDialog_nameLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        newWildCardDialog_nameLabel.setForeground(new java.awt.Color(76, 76, 76));
        newWildCardDialog_nameLabel.setText("Name");

        newWildCardDialog_okButton.setText("OK");
        newWildCardDialog_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWildCardDialog_okButtonActionPerformed(evt);
            }
        });

        newWildCardDialog_rangeLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        newWildCardDialog_rangeLabel.setText("Range");

        newWildCardDialog_enterNameLabel.setText("Enter Wildcard Name:");

        newWildCardDialog_minTextField.setText("1");

        newWildCardDialog_toLabel.setText("To");

        newWildCardDialog_maxTextField.setText("10");

        newWildCardDialog_intervalLabel.setText("By Intervals of:");

        newWildCardDialog_intervalTextField.setText("1");

        javax.swing.GroupLayout newWildCardDialogLayout = new javax.swing.GroupLayout(newWildCardDialog.getContentPane());
        newWildCardDialog.getContentPane().setLayout(newWildCardDialogLayout);
        newWildCardDialogLayout.setHorizontalGroup(
            newWildCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newWildCardDialogLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(newWildCardDialog_enterNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newWildCardDialog_nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(newWildCardDialogLayout.createSequentialGroup()
                .addGroup(newWildCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newWildCardDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newWildCardDialog_rangeLabel))
                    .addGroup(newWildCardDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newWildCardDialog_nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newWildCardDialogLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(newWildCardDialog_okButton))
                    .addGroup(newWildCardDialogLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(newWildCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newWildCardDialogLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(newWildCardDialog_intervalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newWildCardDialog_intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newWildCardDialogLayout.createSequentialGroup()
                                .addComponent(newWildCardDialog_minTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newWildCardDialog_toLabel)
                                .addGap(18, 18, 18)
                                .addComponent(newWildCardDialog_maxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newWildCardDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newWildCardDialog_maxTextField, newWildCardDialog_minTextField});

        newWildCardDialogLayout.setVerticalGroup(
            newWildCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newWildCardDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newWildCardDialog_nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(newWildCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWildCardDialog_enterNameLabel)
                    .addComponent(newWildCardDialog_nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newWildCardDialog_rangeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newWildCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWildCardDialog_minTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newWildCardDialog_toLabel)
                    .addComponent(newWildCardDialog_maxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newWildCardDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWildCardDialog_intervalLabel)
                    .addComponent(newWildCardDialog_intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(newWildCardDialog_okButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moodle Equation Creator");
        setSize(new java.awt.Dimension(550, 480));

        ExpressionsPanel_outputTextAreaScollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ExpressionsPanel_outputTextArea.setEditable(false);
        ExpressionsPanel_outputTextArea.setColumns(20);
        ExpressionsPanel_outputTextArea.setLineWrap(true);
        ExpressionsPanel_outputTextArea.setRows(5);
        ExpressionsPanel_outputTextAreaScollPane.setViewportView(ExpressionsPanel_outputTextArea);

        ExpressionsPanel_directionsLabel1.setText("Enter LaTex code in the box below ");

        ExpressionsPanel_inputLabel.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        ExpressionsPanel_inputLabel.setText("Input:");

        ExpressionsPanel_copyButton.setText("COPY");
        ExpressionsPanel_copyButton.setPreferredSize(new java.awt.Dimension(85, 70));
        ExpressionsPanel_copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpressionsPanel_copyButtonActionPerformed(evt);
            }
        });

        ExpressionsPanel_inputTextArea.setColumns(20);
        ExpressionsPanel_inputTextArea.setLineWrap(true);
        ExpressionsPanel_inputTextArea.setRows(5);
        ExpressionsPanel_inputTextAreaScollPane.setViewportView(ExpressionsPanel_inputTextArea);

        ExpressionsPanel_convertButton.setText("Convert");
        ExpressionsPanel_convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpressionsPanel_convertButtonActionPerformed(evt);
            }
        });

        ExpressionsPanel_directionsLabel2.setText("Click Convert when done");

        ExpressionsPanel_outputLabel.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        ExpressionsPanel_outputLabel.setText("Output:");

        ExpressionsPanel_insertWildcardsButton.setText("<html><p style=\"text-align: center\">Insert<br />Wildcards</p></html>");
        ExpressionsPanel_insertWildcardsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ExpressionsPanel_insertWildcardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpressionsPanel_insertWildcardsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExpressionsPanelLayout = new javax.swing.GroupLayout(ExpressionsPanel);
        ExpressionsPanel.setLayout(ExpressionsPanelLayout);
        ExpressionsPanelLayout.setHorizontalGroup(
            ExpressionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpressionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExpressionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExpressionsPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(ExpressionsPanel_inputTextAreaScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExpressionsPanel_convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExpressionsPanel_inputLabel)
                    .addGroup(ExpressionsPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(ExpressionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExpressionsPanel_directionsLabel2)
                            .addComponent(ExpressionsPanel_directionsLabel1)))
                    .addComponent(ExpressionsPanel_outputLabel)
                    .addGroup(ExpressionsPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(ExpressionsPanel_outputTextAreaScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExpressionsPanel_insertWildcardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ExpressionsPanel_copyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        ExpressionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ExpressionsPanel_convertButton, ExpressionsPanel_copyButton, ExpressionsPanel_insertWildcardsButton});

        ExpressionsPanelLayout.setVerticalGroup(
            ExpressionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpressionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExpressionsPanel_inputLabel)
                .addGap(13, 13, 13)
                .addComponent(ExpressionsPanel_directionsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExpressionsPanel_directionsLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExpressionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExpressionsPanel_inputTextAreaScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ExpressionsPanel_convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(ExpressionsPanel_outputLabel)
                .addGap(18, 18, 18)
                .addGroup(ExpressionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExpressionsPanel_copyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExpressionsPanel_outputTextAreaScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpressionsPanel_insertWildcardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        ExpressionsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ExpressionsPanel_convertButton, ExpressionsPanel_copyButton, ExpressionsPanel_insertWildcardsButton});

        jTabbedPane1.addTab("tab1", ExpressionsPanel);

        WildcardPanel_wildcardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Value", "Min", "Max"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        WildcardPanel_wildcardTable.setFocusable(false);
        WildcardPanel_wildcardTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(WildcardPanel_wildcardTable);

        WildcardPanel_addNewWildcardButton.setText("<html>Add New <br /> Wildcard</html>");
        WildcardPanel_addNewWildcardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WildcardPanel_addNewWildcardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WildcardPanelLayout = new javax.swing.GroupLayout(WildcardPanel);
        WildcardPanel.setLayout(WildcardPanelLayout);
        WildcardPanelLayout.setHorizontalGroup(
            WildcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
            .addGroup(WildcardPanelLayout.createSequentialGroup()
                .addComponent(WildcardPanel_addNewWildcardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        WildcardPanelLayout.setVerticalGroup(
            WildcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WildcardPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WildcardPanel_addNewWildcardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", WildcardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExpressionsPanel_convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpressionsPanel_convertButtonActionPerformed
        // TODO add your handling code here:
        ExpressionsPanel_outputTextArea.setText(NodeTreebuilder.buildTreeFromLaTex(ExpressionsPanel_inputTextArea.getText()).printExpression());
    }//GEN-LAST:event_ExpressionsPanel_convertButtonActionPerformed

    private void ExpressionsPanel_copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpressionsPanel_copyButtonActionPerformed
        // TODO add your handling code here:
        StringSelection selection = new StringSelection(ExpressionsPanel_outputTextArea.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }//GEN-LAST:event_ExpressionsPanel_copyButtonActionPerformed

    private void WildcardPanel_addNewWildcardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WildcardPanel_addNewWildcardButtonActionPerformed
        // TODO add your handling code here:
        newWildCardDialog.setVisible(true);
    }//GEN-LAST:event_WildcardPanel_addNewWildcardButtonActionPerformed

    private void newWildCardDialog_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWildCardDialog_okButtonActionPerformed
        // TODO add your handling code here:
        String name = newWildCardDialog_nameTextField.getText();
        String min = newWildCardDialog_minTextField.getText();
        String max = newWildCardDialog_maxTextField.getText();
        String interval = newWildCardDialog_intervalTextField.getText();

        if(Objects.equals(name, "") || Objects.equals(min, "") || Objects.equals(max, "") || Objects.equals(interval, ""))
        {
            //error
            System.out.println("error");
            return;
        }
        else
        {
            WildCard wildcard = new WildCard();
            wildcard.setName(name);
            wildcard.setValue("{" + name + "}");
            wildcard.setMin(min);
            wildcard.setMax(max);
            wildcard.setInterval(interval);
            WildCardManager.addWildCardToTable(wildcard, WildcardPanel_wildcardTable);
        }
        newWildCardDialog.setVisible(false);    
    }//GEN-LAST:event_newWildCardDialog_okButtonActionPerformed

    private void ExpressionsPanel_insertWildcardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpressionsPanel_insertWildcardsButtonActionPerformed
        // TODO add your handling code here:
        
        String output = WildCardManager.insertWildcardsIntoExpression(ExpressionsPanel_outputTextArea.getText());
        
        
        ExpressionsPanel_outputTextArea.setText(output);
        
    }//GEN-LAST:event_ExpressionsPanel_insertWildcardsButtonActionPerformed

    private void newWildCardDialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_newWildCardDialogWindowActivated
        // TODO add your handling code here:
        newWildCardDialog_nameTextField.setText("");
        newWildCardDialog_minTextField.setText("1");
        newWildCardDialog_maxTextField.setText("10");
        newWildCardDialog_intervalTextField.setText("1");
    }//GEN-LAST:event_newWildCardDialogWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MEC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MEC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MEC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MEC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MEC_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExpressionsPanel;
    private javax.swing.JButton ExpressionsPanel_convertButton;
    private javax.swing.JButton ExpressionsPanel_copyButton;
    private javax.swing.JLabel ExpressionsPanel_directionsLabel1;
    private javax.swing.JLabel ExpressionsPanel_directionsLabel2;
    private javax.swing.JLabel ExpressionsPanel_inputLabel;
    private javax.swing.JTextArea ExpressionsPanel_inputTextArea;
    private javax.swing.JScrollPane ExpressionsPanel_inputTextAreaScollPane;
    private javax.swing.JButton ExpressionsPanel_insertWildcardsButton;
    private javax.swing.JLabel ExpressionsPanel_outputLabel;
    private javax.swing.JTextArea ExpressionsPanel_outputTextArea;
    private javax.swing.JScrollPane ExpressionsPanel_outputTextAreaScollPane;
    private javax.swing.JPanel WildcardPanel;
    private javax.swing.JButton WildcardPanel_addNewWildcardButton;
    private javax.swing.JTable WildcardPanel_wildcardTable;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog newWildCardDialog;
    private javax.swing.JLabel newWildCardDialog_enterNameLabel;
    private javax.swing.JLabel newWildCardDialog_intervalLabel;
    private javax.swing.JTextField newWildCardDialog_intervalTextField;
    private javax.swing.JTextField newWildCardDialog_maxTextField;
    private javax.swing.JTextField newWildCardDialog_minTextField;
    private java.awt.Label newWildCardDialog_nameLabel;
    private javax.swing.JTextField newWildCardDialog_nameTextField;
    private javax.swing.JButton newWildCardDialog_okButton;
    private javax.swing.JLabel newWildCardDialog_rangeLabel;
    private javax.swing.JLabel newWildCardDialog_toLabel;
    // End of variables declaration//GEN-END:variables
}
